#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# common
yabai -m config layout bsp
yabai -m config window_placement second_child
# yabai -m config top_padding 5
# yabai -m config bottom_padding 5
# yabai -m config left_padding 5
# yabai -m config right_padding 5
# yabai -m config window_gap 5

# mouse
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# disabled apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^MongoDB Compass$" manage=off
yabai -m rule --add app="^About This Mac$" manage=off
yabai -m rule --add app="^Postman$" manage=off
yabai -m rule --add app="Docker Desktop$" manage=off
yabai -m rule --add app="Preview$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^escacs$" manage=on
# yabai -m rule --add app="^Electron$" manage=off
# yabai -m rule --add app="^Simulator$" manage=off
# yabai -m rule --add app="WezTerm" manage=off

echo "yabai config loaded..."
