[ -n "$TMUX" ] && export TERM=wezterm

export EDITOR=nvim
export PATH=$HOME/.local/bin:$PATH # local scripts, bins..
export PATH=$HOME/.local/share/nvim/mason/bin:$PATH # language servers, formatters, etc
export PATH=~/go/bin:$PATH # go binaries `go install <pkg>`
export HOMEBREW_AUTO_UPDATE_SECS=604800 # once a week

zstyle ":completion:*" matcher-list "" "m:{a-zA-Z}={A-Za-z}"
bindkey -e

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "/Users/j0rdi/.bun/_bun" ] && source "/Users/j0rdi/.bun/_bun"

# pg
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
